// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC01xTGD-AdqpIkZmWcgFHJIjRt7JXacks',
    appId: '1:996815007127:web:504f923c3a13ff6d1ce8d2',
    messagingSenderId: '996815007127',
    projectId: 'ascma-2bfcd',
    authDomain: 'ascma-2bfcd.firebaseapp.com',
    storageBucket: 'ascma-2bfcd.firebasestorage.app',
    measurementId: 'G-XDJRKSJC74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpgQ_MRhvSZlAWe_Tca9CzmexBMX6qwDk',
    appId: '1:996815007127:android:13be48dcf601530a1ce8d2',
    messagingSenderId: '996815007127',
    projectId: 'ascma-2bfcd',
    storageBucket: 'ascma-2bfcd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2dea2n9U0BFVJRDuGCEf9kW2W5utPrOU',
    appId: '1:996815007127:ios:0b7b90b4debda6801ce8d2',
    messagingSenderId: '996815007127',
    projectId: 'ascma-2bfcd',
    storageBucket: 'ascma-2bfcd.firebasestorage.app',
    iosBundleId: 'com.example.ascma',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2dea2n9U0BFVJRDuGCEf9kW2W5utPrOU',
    appId: '1:996815007127:ios:0b7b90b4debda6801ce8d2',
    messagingSenderId: '996815007127',
    projectId: 'ascma-2bfcd',
    storageBucket: 'ascma-2bfcd.firebasestorage.app',
    iosBundleId: 'com.example.ascma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC01xTGD-AdqpIkZmWcgFHJIjRt7JXacks',
    appId: '1:996815007127:web:effdfb2b67e9ad9b1ce8d2',
    messagingSenderId: '996815007127',
    projectId: 'ascma-2bfcd',
    authDomain: 'ascma-2bfcd.firebaseapp.com',
    storageBucket: 'ascma-2bfcd.firebasestorage.app',
    measurementId: 'G-GBHTYT322D',
  );
}
